# Generated by Django 3.2.3 on 2021-06-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210601_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome da Cidade')),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome_evento',
            field=models.CharField(max_length=100, verbose_name='Nome do Evento'),
        ),
    ]
