# Generated by Django 3.2.3 on 2021-06-01 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210601_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='Cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cidade'),
        ),
    ]
