# Generated by Django 3.2.3 on 2021-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210601_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrocliente',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cadastrocliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
