# Generated by Django 3.2.3 on 2021-06-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210601_1524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Sexo',
        ),
        migrations.AlterModelOptions(
            name='sexo',
            options={'verbose_name_plural': 'Sexo'},
        ),
        migrations.RenameField(
            model_name='cadastrocliente',
            old_name='Cliente',
            new_name='Sexo',
        ),
    ]
