# Generated by Django 3.2.3 on 2021-06-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210601_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastrocliente',
            options={'verbose_name_plural': 'Cadastros'},
        ),
        migrations.AddField(
            model_name='cadastrocliente',
            name='contato',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Celular'),
        ),
    ]
